# Preface {-}

After failing twice in my driving practical test, I took some time off from driving lessons. The reason was, partly, financial. It was also the beginning of the shorter days of winter and I was a bit worried of taking the exam during those cold days when the roads in Edinburgh became a bit tricky to drive. In the next summer, when I tried to contact my driving instructor, to my surprise, I came to know that he had changed his profession. Well, my wife still blames me in secret.To be honest with you, it was not the first time that my driving instructor had stopped training people (though my first instructor had some family responsibilities and took a break). 

So, I went to the third driving instructor, Bill. He was in his late 70s, I guess, and initially I had hard time understand what he was saying. You may think that it's not ideal at all for a driving lesson. But interestingly enough, it worked out in the end and I got my driving license this time. Anyway, Bill used to be an engineer and after his retirement, he started his second career as a driving instructor. On the first day, Bill told me to forget everything I had learned so far on driving. I was a bit shocked indeed with his condescending approach, but when he started the lesson it felt like he was teaching me the grammar of driving - how to control the clutch, how to read the mind the driver of an oncoming vehicle etc. 

By now, you may have started to wander, what does Bill have anything to do with you or this workshop? Bear with me. Each time I think about two R packages, namely `dpylr` and `ggplot2`, they remind me of Bill. In this workshop on exploratory data analysis using *R*, we will learn the grammar of data manipulation and grammar of graphics to draw fancy plots for our exploratory analysis. What you have learned in the previous workshop, was not even the tip of an iceberg of plotting with *R*. Those function that we used were a bit rigid and you have less control over. But here, with the package `ggplot2`, we will shape up the plots as we wish. We will draw layer upon layer to incorporate so many aspects of the data in a single plot. And for the data handling, we will use `dplyr` package. We will add layer of functions, as we think, to build our data structure for downstream analysis. And as a whole, we will try to tell a story with our data and the plots that we will generate today.
